### PR TITLE
fix osx compilation

### PR DESCRIPTION
**Pull request by chenrui333**
This is he actual working solution which I need for homebrew formula upgrade. :)

---

relates to https://github.com/Homebrew/homebrew-core/pull/57422

### CODE REVIEW

**Comment by chenrui333** [comment]
darwin, I believe. I tried the two PRs in this repo (only the way that I used actually works, see my attached PR)

**Comment by hughsie** [comment]
I'm confused why the patch is required given your output is `darwin`...

**Comment by chenrui333** [comment]
It is the syntax issue that I got with the #35

```
gusb/meson.build:44:25: ERROR:  Expecting eol got not.
if host_machine.system() not in ['darwin']
                         ^
```

**Comment by chenrui333** [comment]
Following that PR's idea, this would be the right syntax (`if host_machine.system() != 'darwin'`)

**Comment by chenrui333** [comment]
Just did a quick update and let me know if this works better now. :)

**Comment by hughsie** [comment]
This basically reverts the commit from @bigon here: 16e73d7bfcd9ffb38e9a4ef30ca90c2c8038c2af

I wonder if this is just a case where you need to update the meson version you have on your system (and thus we'd need to bump our required version...)

**Comment by alebcay** [comment]
I believe this is no longer needed after https://github.com/Homebrew/homebrew-core/pull/58926 (if/when merged). We've been building `libgusb` with an older, patched version of `meson` to get around some issues with `rpath` and other library quirks, but the linked PR will update to build with latest `meson`. Hopefully no changes will be necessary here.

**Pull request closed without merging**
