### PR TITLE
Use G_DECLARE_DERIVABLE_TYPE to reduce boilerplate

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by nacho** [comment]
I guess the next step would be to make some of those classes FINAL

**Comment by hughsie** [comment]
We can't do that unfortunately as that would break ABI: https://www.bassi.io/articles/2021/07/27/final-types/

**Comment by nacho** [comment]
I think you broke the ABI anyway no? you removed the priv field of the class struct.

**Comment by hughsie** [comment]
I *think* it's the GUsbDeviceClass that I care about from an ABI point of view (e.g. if anything subclasses GUsbDevice) -- but I'm sure Debian will tell me soon anyway.

**Pull request merged**
