### PR TITLE
Fix a buffer over-read when emulating devices

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 does this need the same fix as fwupd? I couldn't see libglib2.0-doc anywhere!

**Comment by superm1** [comment]
I think the fix in fwupd was masking the real issue; something is missing in the environment.  I'll see if I can figure it out.

**Comment by hughsie** [comment]
Thanks!

**Comment by superm1** [comment]
Try setting this in the environment:
```
DEB_BUILD_MULTIARCH=x86_64-linux-gnu
```

**Comment by superm1** [comment]
And this is the real issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1056185.

**Comment by superm1** [comment]
Cleaner workaround for now:

export DEB_HOST_MULTIARCH=$(dpkg-architecture -qDEB_HOST_MULTIARCH)

**Comment by superm1** [comment]
Should be fixed here: https://tracker.debian.org/news/1479228/accepted-gi-docgen-20231ds-5-source-into-unstable/

**Pull request merged**
