### PR TITLE
Do not try to compile the vapi with no introspection support

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by hughsie** [comment]
@rossburton you need this for meta-oe/recipes-support/libgusb :) I can do a new upstream tarball if this is easier.

**Comment by rossburton** [comment]
We build the vapi/introspection 😀

**Comment by rossburton** [comment]
Ah unless you've got a ghetto target which can't run qemu-user.  I guess our mutual friend wants this backported?

**Comment by hughsie** [comment]
> a ghetto target

Ya, this is some embedded ARM thing.

**Comment by rossburton** [comment]
That's not ghetto and should work :/

**Comment by hughsie** [comment]
> That's not ghetto and should work :/

So I wonder if libgusb is somehow being run without gobject-introspection then?

**Pull request closed without merging**
