### PR TITLE
Add a thin glib wrapper around libusb_endpoint_descriptor

### PR DESCRIPTION
**Pull request by EmmanuelP**
Hi,

Please let me know if you are willing to accept a patch like this that adds a wrapper around the libusb endpoint structure. Not all accessors are implemented yet, and may be it is a bit over enginereed. It could be implemented without adding a new object, just by adding the necessary struct copy and accessors in GUsbInterface.

Cheers,

Emmanuel.

### CODE REVIEW

**Comment by hughsie** [comment]
I think that's a perfectly sane thing to do, thanks! One little niggle then LGTM.

**Comment by EmmanuelP** [comment]
@hughsie which niggle ?

**Comment by hughsie** [comment]
Ohh, maybe Git Hub didn't save my review comment. Basically, `for (i = 0; i < iface->bNumEndpoints; i++)` -> `for (guint i = 0; i < iface->bNumEndpoints; i++)` pls.

**Comment by EmmanuelP** [comment]
Fixed. It is not a common pattern in ligusb code base though.

**Comment by hughsie** [comment]
Can you squash the commits down into one commit please, and force push to update this PR. Then LGTM.

**Comment by EmmanuelP** [comment]
Done.

**Pull request merged**
